AWSTemplateFormatVersion: 2010-09-09
Description: Create VPC

Parameters:
  VpcBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: VPC Cidr Range

  Subnet01Block:
    Type: String
    Default: 10.0.1.0/24
    Description: Cidr Block for subnet within VPC

Metadata:
  AWS::CloudFormation:Interface:
    ParameterGroups:
      - Label:
         default: Dev VPC Network Configuration
         Parameters: 
          - VpcBlock
          - Subnet01Block
    ParameterLabels:
      VpcBlock:
        default: VPC Cide Range
         
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-myVPC"

  Subnet01:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: !Ref Subnet01Block
      AvailabilityZone:
        Fn::Select:
          - '0'
          - Fn::GetAZs:
              Ref: AWS::Region
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Subnet01"

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: PublicSubnets
        - Key: Network
          Value: Public 

  Subnet01RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet01
      RouteTableId: !Ref RouteTable

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref myVPC 

  Route:
    DependsOn: VPCGatewayAttachment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      

Outputs:
  Subnet01Id:
    Description: Subnet01 Id 
    Value: !Ref Subnet01
  VpcId:
    Description: VPC ID 
    Value: !Ref myVPC