# Update Resource Properties - Add new Rule to Security Group

AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance

Resources:
  DevInstances:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02f706d959cedf892
      InstanceType: t2.micro
      KeyName: cnf-key-1
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH SecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0