AWSTemplateFormatVersion: 2010-09-09
Description: Helper Scripts Demo

Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  MySecurityGroupCFN:
    Type: AWS::EC2::SecurityGroup 
    Properties:
      GroupDescription: SecurityGroup for Port 22 and 8080 Inbound
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: '8080'
        ToPort: '8080'
        CidrIp: 0.0.0.0/0
  MyVMInstance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Metadata:
      Comment: Deploy a Tomcat Appication
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              java-1.8.0-openjdk.x86_64: []
              java-1.8.0-openjdk-devel: []
              tomcat8: []
          groups:
            groupone: {}
            grouptwo:
              gid: "501"
          users:
            userone:
              groups:
                - groupone
                - grouptwo
              uid: "501"
              homeDir: "/tmp"
          sources:
            /tmp: "https://mycfn-init-bucket.s3.us-east-2.amazonaws.com/cfn/demo2.zip"
          files:
            "/etc/cfn/cfn-hub.conf":
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=7
              mode: "000400"
              owner: "root"
              group: "root"
            "/etc/cfn/hooks.d/cfn-auto-reloader.conf":
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.MyVMInstance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource MyVMInstance --region ${AWS::Region}
              mode: "000400"
              owner: "root"
              group: "root"
          commands:
            test1:
              command: "chmod 755 demo.war"
              cwd: "/tmp"
            test2:
              command: "sudo yum erase -y java-1.7.0-openjdk.x86_64"
              cwd: "~"
            test3:
              command: "rm -rf demo*"
              cwd: "/var/lib/tomcat8/webapps"
            test4:
              command: "cp demo.war /var/lib/tomcat8/webapps"
              cwd: "/tmp"
          services:
            sysvinit:
              tomcat8:
                enabled: "true"
                ensureRunning: "true"
    Properties:
      ImageId: ami-02f706d959cedf892
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - !Ref MySecurityGroupCFN
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash -xe
            # Get latest cfn packages
            yum update -y aws-cfn-bootstrap
            # Start cfn-init and install from (packages,sources,files,commands and services)
            /opt/aws/bin/cfn-init -s ${AWS::StackId} -r MyVMInstance --region ${AWS::Region} || error_exit 'Failed to run cfn-init'
            # Signal status from cfn-hub
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource MyVMInstance --region ${AWS::Region}
            # Start cfn-hub daemon
            /opt/aws/bin/cfn-hub || error_exit 'Failed to start cfn-hub'

Outputs:
  AppURL:
    Description: Appication URL to access
    Value: !Sub 'http://${MyVMInstance.PublicDnsName}:8080/demo'